# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fd7c1f27017432098c8488827d07bdf70d0ab7f9db3b77f247df94a262e339a6fb37b1f0896b17fbfb849c23fa16ee9b0a48a45ac6195f712afcaaa8acfa33e

test:
  secret_key_base: 94caee7104f7b73525d40a43d551e2d3d9cf4e1408c9f6843f2dfa0a33330cb9e3c0f8bf89643ace4026c6a699b4d9d08828ab1d193d1f7398bd190ed6cd3255

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
